all: tester.c lists.c tokenizer.c
	gcc -o tokenizer tester.c lists.c tokenizer.c

test1:
	cat token-test.input.00 | ./tokenizer | diff token-test.output.00 -

test1:
	cat token-test.input.01 | ./tokenizer | diff token-test.output.01 -

testt2:
	cat token-test.input.02 | ./tokenizer | diff token-test.output.02 -

test3:
	cat token-test.input.03 | ./tokenizer | diff token-test.output.03 -

test4:
	cat token-test.input.04 | ./tokenizer | diff token-test.output.04 -

test5:
	cat token-test.input.05 | ./tokenizer | diff token-test.output.05 -

test6:
	cat token-test.input.06 | ./tokenizer | diff token-test.output.06 -

test7:
	cat token-test.input.07 | ./tokenizer | diff token-test.output.07 -

test8:
	cat token-test.input.08 | ./tokenizer | diff token-test.output.08 -

test9:
	cat token-test.input.09 | ./tokenizer | diff token-test.output.09 -

test10:
	cat token-test.input.10 | ./tokenizer | diff token-test.output.10 -

test11:
	cat token-test.input.11 | ./tokenizer | diff token-test.output.11 -

test12:
	cat token-test.input.12 | ./tokenizer | diff token-test.output.12 -

test13:
	cat token-test.input.13 | ./tokenizer | diff token-test.output.13 -

test14:
	cat token-test.input.14 | ./tokenizer | diff token-test.output.14 -

test15:
	cat token-test.input.15 | ./tokenizer | diff token-test.output.15 -

test16:
	cat token-test.input.16 | ./tokenizer | diff token-test.output.16 -